
services:

  traefik:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false" # don't expose all containers by default
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=dev-nau@krysinfo.fr"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt_data:/letsencrypt

  dufs:
    image: sigoden/dufs
    volumes:
      - dufs-data:/data
    command: -A -p 5000 /data

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
    volumes:
      - mysql-data:/var/lib/mysql
    secrets:
      - mysql_root_password
      - mysql_user_password

  api:
    image: ghcr.io/krysinfo-dev/mysmartfamily2-api:${COMMIT_HASH:-latest}
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
    environment:
      - BREVO_API_KEY=/run/secrets/brevo_api_key
    secrets:
      - brevo_api_key
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`smf2.krysinfo.fr/api`)"
      - "traefik.http.routers.api.middlewares=strip-prefix@docker,redirect-to-https@docker"
      - "traefik.http.routers.api-secure.entrypoints=websecure"
      - "traefik.http.routers.api-secure.rule=Host(`smf2.krysinfo.fr/api`)"
      - "traefik.http.routers.api-secure.middlewares=strip-prefix@docker"
      - "traefik.http.routers.api-secure.tls=true"
      - "traefik.http.routers.api-secure.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.strip-prefix.stripprefix.prefixes=/api"
      - "traefik.http.services.api-service.loadbalancer.server.port=8087"
    depends_on:
      - dufs
      - mysql

  front:
    image: ghcr.io/krysinfo-dev/mysmartfamily2-front:${COMMIT_HASH:-latest}
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.routers.web.rule=Host(``smf2.krysinfo.fr`)"
      - "traefik.http.routers.web.middlewares=redirect-to-https@docker"
      - "traefik.http.routers.web-secure.entrypoints=websecure"
      - "traefik.http.routers.web-secure.rule=Host(``smf2.krysinfo.fr`)"
      - "traefik.http.routers.web-secure.tls=true"
      - "traefik.http.routers.web-secure.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.services.web-service.loadbalancer.server.port=8501"
    depends_on:
      - api

volumes:
  mysql-data:
  dufs-data:
  letsencrypt_data:

secrets:
  brevo_api_key:
    external: true
  mysql_root_password:
    external: true
  mysql_user_password:
    external: true
