version: '3.8'

services:
  traefik:
    image: traefik:v2.11
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.email=ton@mail.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-certificates:/letsencrypt
    networks:
      - web

  api:
    image: ghcr.io/krysInfo.dev/api:latest
    restart: on-failure
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
    environment:
      - BREVO_API_KEY=/run/secrets/brevo_api_key
    secrets:
      - brevo_api_key
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.msf2.krysinfo.fr`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=le"
    networks:
      - web
      - internal

  front:
    image: ghcr.io/krysInfo.dev/front:latest
    restart: on-failure
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`msf2.krysinfo.fr`)"
      - "traefik.http.routers.front.entrypoints=websecure"
      - "traefik.http.routers.front.tls.certresolver=le"
    networks:
      - web

  dufs:
    image: sigoden/dufs
    volumes:
      - dufs-data:/data
    command: -A -p 5000 /data
    networks:
      - internal

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
    volumes:
      - mysql-data:/var/lib/mysql
    secrets:
      - mysql_root_password
      - mysql_user_password
    networks:
      - internal

volumes:
  mysql-data:
  dufs-data:
  traefik-certificates:

networks:
  web:
    external: true
  internal:

secrets:
  brevo_api_key:
    external: true
  mysql_root_password:
    external: true
  mysql_user_password:
    external: true
